version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  api:
    image: api:latest
    depends_on:
      - clickhouse
      - kafka
      - postgres
    environment:
      - VIRTUAL_HOST=event2.voidpet.com
      - VIRTUAL_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  web:
    image: web:latest
    environment:
      - VIRTUAL_HOST=event2.voidpet.com
      - VIRTUAL_PORT=3000

  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: voidpulse
    depends_on:
      - kafka
      - zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1001
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: voidpulse
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: true
  clickhouse-data:
    external: true
  caddy_data:
    external: true
  caddy_config:
