version: '3.8'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - overlay-net

  node-app:
    image: node-app-image
    networks:
      - overlay-net
    depends_on:
      - clickhouse
      - kafka
      - postgres
    deploy:
      labels:
        - "caddy.reverse_proxy=to http://node-app:3000"
        - "caddy.reverse_proxy.header_up=Host event2.voidpet.com"
        - "caddy.reverse_proxy.path=/trpc/*"
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.5
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  next-app:
    image: next-app-image:latest
    networks:
      - overlay-net
    deploy:
      labels:
        - "caddy.reverse_proxy=to http://next-app:3000"
        - "caddy.reverse_proxy.header_up=Host event2.voidpet.com"

  clickhouse:
    image: yandex/clickhouse-server
    networks:
      - overlay-net
    depends_on:
      - kafka
      - zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - overlay-net

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - overlay-net

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - overlay-net

networks:
  overlay-net:
    driver: overlay

volumes:
  db-data:
